bot_user_id = '@botname:domain.org'
# bot password is specified via the BOT_PASSWORD environment variable
reporting_room_id = '!roomid:domain.org'
admin_room_id = '!adminroomid:domain.org'
notice_emoji = '⭕'
restrict_notice = true
verbs = ["reports", "says", "announces"]
min_length = 30
# Set to '' to disable text response
ack_text = "✅ Thanks for the report {{user}}, I'll store your update!"
update_config_command = "sh /data/update_config.sh"
editors = [
    '@user1:domain.io',
    '@user2:domain.com',
]

[[sections]]
emoji = '🔵'
name = 'core'
title = 'Core Apps and Libraries'
order = 100
usual_reporters = ['@user1:domain.io']

[[sections]]
emoji = '🛰️'
name = 'third-party'
title = 'Third Party Projects'
order = 200
usual_reporters = []

[[projects]]
emoji = '📻'
name = 'shortwave'
title = 'Shortwave'
description = 'Internet radio player with over 25000 stations.'
website = 'https://gitlab.gnome.org/World/Shortwave'
default_section = 'third-party'

[[projects]]
emoji = '⬇️'
name = 'fragments'
title = 'Fragments'
description = 'Easy to use BitTorrent client.'
website = 'https://gitlab.gnome.org/World/Fragments'
default_section = 'third-party'
